# Generated by Django 2.2.11 on 2020-04-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaluseridentifier',
            options={'verbose_name': 'External User', 'verbose_name_plural': 'External Users'},
        ),
    ]
